### ISSUE TITLE
NO connection

### ISSUE THREAD

**Issue by miksyyy** [Rahulb7/Scholarship-management-system#7]
When i log in i get this error, pls help me how to fix this.

SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.

**Comment by Jeff-lazo** [comment]
This is my problem too actually how to fix this?

**Comment by Rahulb7** [comment]
This is a static website, I used MySQL to store my data locally. Try implementing on your machine and create a demo database. The n it should not give error.
